version: '3.9'
services:
  db:
    image: postgres:14
    env_file: .env
    expose:
      - '5432'
    volumes:
      - group-project:/var/lib/postgresql/data
      - ./src/init_data:/docker-entrypoint-initdb.d
  web:
    image: node:lts
    user: 'node'
    working_dir: /repository
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./:/repository
    #Only one command line below can be uncommented at a time
    #command: 'npm start' #Uncomment if you wish view the website through local host
    command: 'npm run testandrun' #Uncomment if you wish to run the test cases. Breaks viewing website
volumes:
  group-project: